server {
    listen 80;
    server_name jobcon.home;
    index index.php index.html index.htm;

    location / {
        proxy_pass http://jobcon_nginx:80;
        proxy_set_header Host $host;
    }
}