services:
  jobconphp:
    build: ./docker/config/php/74
    container_name: jobconphp
    working_dir: /var/www/newton/jobcon
    ports:
      - 4000:9000
    volumes:
      - /home/newton/.config:/var/www/.config
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/newton/jobcon
    restart: unless-stopped
    networks:
      homelab:
        aliases:
          - jobcon.localhost
networks:
  homelab:
    name: homelab_lan
    external: true
