services:
  jobcon-php:
    image: homelab/php:8.2-fpm
    container_name: jobcon-php
    working_dir: /var/www/html/jobcon
    volumes:
      - ./src:/var/www/html/jobcon
    restart: unless-stopped
    networks:
      - proxy
      - internal
  jobcon-nginx:
    image: nginx:alpine
    container_name: jobcon-nginx
    working_dir: /var/www/html/jobcon
    volumes:
      - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html/jobcon
    depends_on:
      - jobcon-php
    restart: unless-stopped
    networks:
      - proxy
networks:
  proxy:
    external: true
  internal:
    external: true
