services:
  jobcon_ws:
    image: nginx:latest
    container_name: jobcon_ws
    working_dir: /var/www/html/jobcon/src
    volumes:
      - "./docker/config/nginx/conf.d:/etc/nginx/conf.d"
      - .:/var/www/html/jobcon
    depends_on:
      - jobcon_aps
    restart: unless-stopped
    networks:
      - jobcon
      - homelab
  jobcon_aps:
    build: 
      context: .
      dockerfile: ./docker/config/php/82/Dockerfile
    container_name: jobcon_aps
    working_dir: /var/www/html/jobcon/src
    volumes:
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/html/jobcon
    restart: unless-stopped
    networks:
      - jobcon
      - homelabjobcon_dbs:
    image: mysql:latest
    container_name: jobcon_dbs
    ports:
      - ${DATABASE_SERVER_PORT}:3306
    volumes:
      - ./docker/volumes/mysqldata:/var/lib/mysql
      - ./docker/dumps:/var/www/dumps
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_SERVER_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_SERVER_DATABASE}
      - MYSQL_USER=${DATABASE_SERVER_USER}
      - MYSQL_PASSWORD=${DATABASE_SERVER_PASSWORD}
    restart: unless-stopped
    networks:
      - jobcon
networks:
  jobcon:
  homelab:
    external: true
    name: homelab_lan
