services:
  jobconweb:
    image: nginx:latest
    container_name: jobcon_nginx
    hostname: jobcon_nginx
    working_dir: /var/www/jobcon
    ports:
      - 81:80
    volumes:
      - .:/var/www/jobcon
      - ./docker/config/nginx/sites-available:/etc/nginx/sites-available
      - ./docker/config/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      lan:
  jobconphp:
    # image: php:8.2-fpm
    build: ./docker/config/php/74
    container_name: jobcon_php
    hostname: jobcon_php
    working_dir: /var/www/jobcon
    ports:
      - 9000:9000
    volumes:
      - /home/newton/.config:/var/www/.config
      - .:/var/www/jobcon
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
    restart: unless-stopped
    networks:
      lan:
  jobconmysql:
    container_name: jobcon_mysql
    image: mysql:latest
    ports:
     - 3307:3306  
    volumes:
      - ./docker/volumes/mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=jobcon
      - MYSQL_USER=jobcon
      - MYSQL_PASSWORD=jobcon123
    #  - MYSQL_ALLOW_EMPTY_PASSWORD=1
    # command: --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0
    restart: unless-stopped
    networks:
      lan:
networks:
  lan:
    driver: bridge
