sonar.projectKey=jobcon
sonar.projectName=jobcon

# Nunca coloque token diretamente aqui
sonar.modules=jobcon-mobile,jobcon-rpa,jobcon-web,k8s


# -----------------------------
# Módulo 1: jobcon-mobile
# -----------------------------
jobcon-mobile.sonar.projectName=jobcon-mobile
jobcon-mobile.sonar.projectBaseDir=jobcon-mobile
jobcon-mobile.sonar.sources=.
jobcon-mobile.sonar.exclusions=\
  node_modules/**

# ---------------------------------------------
# Módulo 2: jobcon-rpa
# ---------------------------------------------
jobcon-rpa.sonar.projectName=jobcon-rpa
jobcon-rpa.sonar.projectBaseDir=jobcon-rpa
jobcon-rpa.sonar.sources=src
jobcon-rpa.sonar.tests=src/tests
jobcon-rpa.sonar.exclusions=\
    node_modules/**,\
    src/tests/**

# ---------------------------------------------
# Módulo 3: jobcon-web
# ---------------------------------------------
jobcon-web.sonar.projectName=jobcon-web
jobcon-web.sonar.projectBaseDir=jobcon-web
jobcon-web.sonar.sources=.
jobcon-web.sonar.tests=tests
jobcon-web.sonar.exclusions=\
    storage/**,\
    vendor/**,\
    tests/**