server {
    listen 80;
    server_name rpajobcon.localhost;
    index index.html index.htm;
    root /var/www/html/rpa-jobcon
    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }
}
