<?php
return [
    'SLACK_BOT_USER_OAUTH_TOKEN' => env('SLACK_BOT_USER_OAUTH_TOKEN'),
    'SLACK_BOT_USER_DEFAULT_CHANNEL' => env('SLACK_BOT_USER_DEFAULT_CHANNEL'),
    'SLACK_BOT_USER_CHANNEL_ID' => env('SLACK_BOT_USER_CHANNEL_ID'),
];
