FROM nginx:latest

RUN mkdir -p /var/cache/nginx/client_temp && \
    chown -R nginx:nginx /var/cache/nginx

VOLUME [ "./www/site" ]
WORKDIR /var/www/site

COPY ./config/default.conf /etc/nginx/conf.d/default.conf
COPY ./www/site/index.html /var/www/site/index.html

EXPOSE 8084

# # Change uid and gid of apache to docker user uid/gid
# RUN usermod -u 1000 www-data && groupmod -g 1000 www-data
# USER www-data