version: '3'
services:
  mwserver:
    build: .
    container_name: mwebserver
    ports:
      - 8181:80
      - 8100:8100
    volumes:
      - .:/var/www/html/jobcon-mobile
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    # command:  npm start --prefix api
    networks:
      lan:
networks:
  lan:
