server {
    listen 80;
    server_name jobcon.localhost;
    index index.php index.html index.htm;
    root /var/www/html/jobcon/src/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass jobcon_aps:9000;
        fastcgi_index   index.php;
        fastcgi_param   SCRIPT_FILENAME   $document_root$fastcgi_script_name;
        fastcgi_param   SCRIPT_NAME       $fastcgi_script_name;        
    }

    location ~ /\. {
        deny all;
    }
}