version: '3'
services:
  rpa:
    build: .
    container_name: rpa
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html/jobcon-rpa
    restart: unless-stopped
    # command:  npm start --prefix api
    networks:
      lan:
networks:
  lan:
