services:
  webserver:
    image: nginx:latest
    container_name: webserver
    hostname: jobcon.homelab
    working_dir: /var/www/html/jobcon-web
    volumes:
      - .:/var/www/html/jobcon-web
      - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - appserver
    restart: unless-stopped
    networks:
      - oldjobcon
      - homelab

  appserver:
    build: 
      context: .
      dockerfile: ./docker/config/php/82/Dockerfile
    container_name: appserver
    working_dir: /var/www/html/jobcon-web
    volumes:
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/html/jobcon-web
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    restart: unless-stopped
    networks:
      - oldjobcon
      - homelab

networks:
  oldjobcon:
  homelab:
    external: true
    name: homelab_lan
