# Dockerfile
FROM nginx:latest

#
LABEL maintainer="Newton Gonzaga Costa<ncosta.rj@gmail.com>" \
      description="Imagem para desenvolvimento com rpa"

#
VOLUME [ "/var/www/html" ]

#
WORKDIR /var/www/html/app

# Expose the default port
EXPOSE 80 3000 4200

# Basic packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    cron \
    vim \
    htop \
    git \
    locales \
    cron \
    zlib1g-dev \
    software-properties-common \
    build-essential \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i -- 's/# pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/g' /etc/locale.gen \
    && locale-gen \
    && sed -i -- 's/Etc\/UTC/America\/Sao_Paulo/g' /etc/timezone \
    && sed -i -- 's/# alias ll/alias ll/g' /root/.bashrc \
    && unlink /etc/localtime \
    && ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
    # && sed -i -- 's/localhost/localhost,big.server.com/g' /etc/hosts

#
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \
    && apt-get update && apt-get install -y nodejs \
    && npm i -g forever pm2 nodemon @angular/cli

ENV LC_ALL pt_BR.UTF-8

# Copy conf file
COPY conf/nginx/default.conf /etc/nginx/conf.d

# CMD forever start /var/www/html/app/server.js

RUN usermod -u 1000 www-data && groupmod -g 1000 www-data

WORKDIR /var/www/html/rpa-jobcon

USER www-data
